### ISSUE TITLE
compile the codes and find some problems with the Halide part

### ISSUE THREAD

**Issue by xianming90** [timothybrooks/hdr-plus#7]
Hi, Tim,

We try to compile the codes and find some problems with the Halide part.
We want to know what version of Halide used in the compilation of your codes,
so we can download the correct one.

Could you kindly provide the info?

Thank you

**Comment by lisongnan1982** [comment]
I tried several Halide versions and found version 2016/10/22 works.

**Comment by oya163** [comment]
Do we need to have specific gcc version. Can you please tell me which gcc version/halider version, you are currently using to run this program smoothly?

**Comment by lisongnan1982** [comment]
I used gcc 5.4.0 on Linux 16.04, and the downloaded halide is 2016/10/22
(halide-linux-64-gcc53-trunk-aa5d5514f179bf0ffe1a2dead0c0eb7300b4069a.tgz).
I have compiled the code but haven't run it yet. Hope the information is
helpful.

**Comment by Trinkle23897** [comment]
Just replace Halide::Image to Halide::Buffer and it's work!

**Comment by jiangbaige** [comment]
Successfully compiled the code using the method of Trinkle23897，How to use this project to compile datasets provided by author on google research

**Comment by Trinkle23897** [comment]
@jiangbaige This work takes me a couple of weeks……you need to replace rggb patterns to bggr patterns in demosaic part, and need to fix a bug when g1==0, also try to change white level and black level in the code to fit with google's dng arguments, and finally you'll find the code only works on the case which the height of image is less than the width, other wise it will output pink picture. I'm not sure whether other bugs in the code I'm not written above, because I can't remember well...

**Comment by jiangbaige** [comment]
@Trinkle23897 Indeed, my output has always been a pink picture

**Comment by jiangbaige** [comment]
@Trinkle23897 the height of my input image is less than the width, however, my output has always been a pink picture.

**Comment by shockjiang** [comment]
@Trinkle23897 I'm trying to build the code on current Halide, do you have any suggestion? I looked through your discussion, and two methods are proposed: 
1/ use an old halide version, 2016/10/22
2/ change Image to Buffer and others.
Which one do you think is better?

**Comment by lisongnan1982** [comment]
Changing Image to Buffer works well. Should be a better solution. I deleted my replies about using 2016/10/22 version of Halide.

**Comment by Trinkle23897** [comment]
@shockjiang change image to buffer is better

**Comment by Trinkle23897** [comment]
@jiangbaige 可以加我微信，微信号就是我的github昵称

**Comment by shockjiang** [comment]
@Trinkle23897 let me make it clear on fixing the issue:
settings: code here + latest halide + LLVM4.0(suggested by halide)
step to fix:
1/ change all the Image in this hdr+ code to Buffer
2/ "eplace rggb patterns to bggr patterns in demosaic part, and need to fix a bug when g1==0, also try to change white level and black level in the code to fit with google's dng arguments, and finally you'll find the code only works on the case which the height of image is less than the width, otherwise it will output pink picture"


Am I right here?

**Comment by shockjiang** [comment]
@jiangbaige I'm also working on this project, shall I wechat you? my id is: swordguy

**Comment by timothybrooks** [comment]
To use the latest version of Halide, switch Halide::Image to Halide::Buffer (as @Trinkle23897 notes). This is due to a change in Halide after the project was initially made. It would be great to update this in the master branch, so please feel free to create a pull request.

Pink results are due to incorrect while level and black level for your camera. The white level and black level I use are specifically for my Canon 5D III. These values can typically be retrieved from the image metadata.

You can reverse the width and height values to run on a vertical image. Typically, raw image pipelines keep images in the native horizontal orientation while processing, and rotate vertical image at the end.

**Comment by eliver8801** [comment]
In file included from /home/eliver/Halide/hdr-plus/src/HDRPlus.cpp:2:0:
/home/eliver/Halide/hdr-plus/src/halide_load_raw.h: In function ‘bool Halide::Tools::load_raw(const string&, uint16_t*, int, int)’:
/home/eliver/Halide/hdr-plus/src/halide_load_raw.h:50:93: error: too many arguments to function
     if (!check(f.f != nullptr, "File %s could not be opened for reading\n", filename.c_str())) return false;
                                                                                             ^
In file included from /home/eliver/Halide/hdr-plus/src/HDRPlus.cpp:2:0:
/home/eliver/Halide/hdr-plus/src/halide_load_raw.h:66:135: error: too many arguments to function
     if (!check(in_width == width, "Input image '%s' has width %d, but must must have width of %d\n", filename.c_str(), in_width, width)) return false;
                                                                                                                                       ^
/home/eliver/Halide/hdr-plus/src/halide_load_raw.h:68:141: error: too many arguments to function
     if (!check(in_height == height, "Input image '%s' has height %d, but must must have height of %d\n", filename.c_str(), in_height, height)) return false;
                                                                                                                                             ^
In file included from /home/eliver/Halide/hdr-plus/src/HDRPlus.cpp:2:0:
/home/eliver/Halide/hdr-plus/src/halide_load_raw.h: In instantiation of ‘bool Halide::Tools::load_raw(const string&, uint16_t*, int, int) [with bool (* check)(bool, const char*) = Halide::Tools::Internal::CheckFail; std::string = std::basic_string<char>; uint16_t = short unsigned int]’:
/home/eliver/Halide/hdr-plus/src/HDRPlus.cpp:85:66:   required from here
/home/eliver/Halide/hdr-plus/src/halide_load_raw.h:50:93: error: too many arguments to function
     if (!check(f.f != nullptr, "File %s could not be opened for reading\n", filename.c_str())) return false;
                                                                                             ^
In file included from /home/eliver/Halide/hdr-plus/src/HDRPlus.cpp:2:0:
/home/eliver/Halide/hdr-plus/src/halide_load_raw.h:66:135: error: too many arguments to function
     if (!check(in_width == width, "Input image '%s' has width %d, but must must have width of %d\n", filename.c_str(), in_width, width)) return false;
                                                                                                                                       ^
/home/eliver/Halide/hdr-plus/src/halide_load_raw.h:68:141: error: too many arguments to function
     if (!check(in_height == height, "Input image '%s' has height %d, but must must have height of %d\n", filename.c_str(), in_height, height)) return false;
                                                                                                                                             ^
CMakeFiles/hdrplus.dir/build.make:62: recipe for target 'CMakeFiles/hdrplus.dir/src/HDRPlus.cpp.o' failed
make[2]: *** [CMakeFiles/hdrplus.dir/src/HDRPlus.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/hdrplus.dir/all' failed
make[1]: *** [CMakeFiles/hdrplus.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

How can I fix this problem,somebody can help me?

**Comment by www571859177** [comment]
@Trinkle23897  “need to fix a bug when g1==0”,can you explain it in details? I don't know how to fix it ,thanks very much!

**Comment by Entropy512** [comment]
@eliver8801 It was broken by https://github.com/halide/Halide/commit/dbccf16b3b8b682a9cb597042ee8f61d588bff22#diff-3560d2b032ba793419a4d74598540171 - but I haven't had time to figure out a good way to solve it.

**Comment by zhangzhipengtingting** [comment]
@jiangbaige Have you fixed this issue(pink picture)?Could you share me the solution，thanks.

**Comment by hiepgaf** [comment]
Hi @Trinkle23897,
how to replace rggb with bggr as you mentioned?
Can you shared your code?
Thanks.

**Comment by timothybrooks** [comment]
Closing as new pull requests to alleviate Halide compatibility issues have been merged. Please reopen if the problem persists.
